[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Technology"
  url = "categories/technology/"
  weight = -109

[[main]]
  name = "Life"
  url = "categories/life/"
  weight = -108

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/Jerrysmd##"



# [[social]]
#   name = "twitter"
#   weight = 2
#   url = "https://twitter.com/ZJ1IFlOSupZnr7W##"
# [[social]]
#   name = "instagram"
#   weight = 3
#   url = "https://www.instagram.com/0x4c2/#"


# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"