name: github pages

on:
  workflow_dispatch:
  push:
    branches:
    - blog-source
  pull_request:
      branches:
      - blog-source

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          #fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/blog-source' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: 'BADKNNRXHD'
          algolia_api_key: '7a8c2923330a44bdd9985698e3f28e0c'
          file: 'index.json'
