name: github pages

on:
  workflow_dispatch:
  push:
    branches:
    - blog-source
  pull_request:
      branches:
      - blog-source

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          #fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/blog-source' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          
  algolia:
    runs-on: ubuntu-latest

    needs: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: Algolia Docsearch Uploader
        uses: guzhongren/algolia-docsearch-upload-action@v2.0.0
        env:
          FILE_PATH: "index.json"
          APPLICATION_ID: "BADKNNRXHD"
          ADMIN_API_KEY: ${{secrets.ALGOLIA_API_KEY}}
          INDEX_NAME: "index"
